name: CI Build & Publish

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew
      - name: Setup GPG
        run: |
          echo "${{ secrets.PGP_BINARY_PRIVATE_KEY }}" | base64 -d > private.key
      - name: Publish package to Maven Central
        run: |
          ./gradlew clean build publishToMavenCentral --no-build-cache --no-daemon --stacktrace --no-parallel \
            -Psigning.secretKeyRingFile=$PWD/private.key \
            -Psigning.keyId=${{ secrets.PGP_KEY_ID }} \
            -Psigning.password=${{ secrets.PGP_PASSWORD }}
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}